if(tw){tw.$1=document.querySelector.bind(document);tw.isDOM=function(a){return"HTMLElement"in window?a&&a instanceof HTMLElement:!(!a||"object"!==typeof a||1!==a.nodeType||!a.nodeName)};tw.supportsCssTransitions=function(a){for(var b=["","webkit","moz","ms","o"],d,c=0,e=b.length;c<e;c++)if(d=0===c?"transition":"Transition","undefined"!==typeof a[b[c]+d])return!0;return!1}(document.createElement("div").style);tw.run=function(a,b){var d=tw.setDefFn(b.onStep),c=tw.setDefFn(b.onComplete);b.$target=tw.getTarget(a);
b.dur="undefined"!==typeof b.dur?b.dur:1;b.delay=b.delay||0;b.paused="undefined"===typeof b.delay||0===b.delay?!1:!0;b.from=b.from||tw.getFromValue(b);var e=tw.tween(b.from,b.to,b.dur,function(a){b.data=a;b.onTick(b);d(a)},function(){c()},b.paused);e.tm=setTimeout(function(){e.tm=null;e&&(e.paused=!1)},1E3*b.delay);return e};tw.getCssProperty=function(a,b){return window.getComputedStyle(a,null).getPropertyValue(b)};tw.getFromValue=function(a){if("x"===a.toTween)a=tw.supportsCssTransitions?tw.getVal(a.$target,
"translateX")||0:tw.getCssProperty(a.$target,"left")||0;else if("y"===a.toTween)a=tw.supportsCssTransitions?tw.getVal(a.$target,"translateY")||0:tw.getCssProperty(a.$target,"top")||0;else if("rotate"===a.toTween||"scaleX"===a.toTween)a=tw.getVal(a.$target,a.toTween)||0;else if("scale"===a.toTween||"scaleX"===a.toTween)a=tw.getVal(a.$target,"scaleX")||1;else{var b=1;"opacity"===a.toTween&&(b=0);a=tw.getCssProperty(a.$target,a.toTween)||b}return parseFloat(a)};tw.getTarget=function(a){return"string"===
typeof a?tw.$1(a):a};tw.setDefFn=function(a){return a||function(){}};tw.trString=function(a){return"undefined"!==typeof a.transform?"transform":"undefined"!==typeof a.webkitTransform?"webkitTransform":"undefined"!==typeof a.MozTransform?"MozTransform":"undefined"===typeof a.msTransform&&a.msTransform?"msTransform":!1}(document.createElement("div").style);tw.getVal=function(a,b){var d=a.style[tw.trString],c=d.indexOf(b);return-1<c?(d=d.substr(c+b.length+1),d.substr(0,d.indexOf(")"))):null};tw.transform=
function(a,b,d){var c=a.style[tw.trString],e=tw.getVal(a,b);b=e?c.split(b+"("+e+")").join(b+"("+d+")"):c+" "+b+"("+d+")";if(a instanceof Array)for(c=0;c<a.length;c++)a[c].style[style]=d,a[c].style.webkitTransform=b,a[c].style.transform=b;else a.style[tw.trString]=b};tw.setStyle=function(a,b,d){if(a instanceof Array)for(var c=0;c<a.length;c++)a[c].style[b]=d;else a.style[b]=d};tw.x=function(a,b){b.toTween="x";b.onTick=function(a){tw.supportsCssTransitions?tw.transform(a.$target,"translateX",a.data.val+
"px"):a.$target.style.left=a.data.val+"px"};return tw.run(a,b)};tw.y=function(a,b){b.toTween="y";b.onTick=function(a){tw.supportsCssTransitions?tw.transform(a.$target,"translateY",a.data.val+"px"):tw.setStyle(a.$target,"top",a.data.val+"px")};return tw.run(a,b)};tw.scale=function(a,b){b.toTween="scale";b.onTick=function(a){tw.transform(a.$target,"scaleX",a.data.val);tw.transform(a.$target,"scaleY",a.data.val)};return tw.run(a,b)};tw.rotate=function(a,b){b.toTween="rotate";b.onTick=function(a){tw.transform(a.$target,
"rotate",a.data.val+"deg")};return tw.run(a,b)};tw.opacity=function(a,b){b.toTween="opacity";b.onTick=function(a){tw.setStyle(a.$target,"opacity",a.data.val)};return tw.run(a,b)};tw.m=function(a,b,d,c){for(var e=0;e<a.length;e++){var f=JSON.parse(JSON.stringify(d));e===a.length-1&&(f.onComplete=c);tw[b](a[e],f)}};var tw=tw||{};tw.Q=function(a){this.q=[];this.index=0;this.currTw=null;this.data=a;this.goNext=!0;this.id="Q"+tw.Q.getId();this.setup(this.data)};tw.Q.prototype={};tw.Q.prototype.setup=function(){this.data.onComplete&&
(this.onComplete=this.data.onComplete);tw.Q.all[this.id]=this};tw.Q.prototype.add=function(a){this.q.push(a)};tw.Q.prototype.onComplete=function(){};tw.Q.prototype.restart=function(){this.play()};tw.Q.prototype.play=function(){this.goNext=!0;this.index=0;this.currTw=null;this.nextFn.call(this)};tw.Q.prototype.stop=function(){this.goNext=!1;this.currTw&&this.currTw.kill();this.currTw=null;this.index=0};tw.Q.prototype.nextFn=function(){var a=this;if(a.index>=a.q.length)a.onComplete();else{var b=a.q[a.index];
b&&(b.delay=b.delay||0,a.currTw=tw[b.what](b.t,{to:b.to,dur:b.dur,delay:b.delay,onComplete:function(){a.goNext&&a.nextFn.call(a)}}),a.index++)}};tw.Q.prototype.kill=function(){this.stop();delete tw.Q.all[this.id]};tw.Q.all={};tw.Q.getId=function(){return(new Date).getTime()+parseInt(100*Math.random()).toString()};tw.Q.get={$1:document.querySelector.bind(document),$2:document.querySelectorAll.bind(document)}}else console.error("Load tinyTween first.");
